[package]
name = "constraint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-lexer = { path = "../regex-lexer" }
lazy_static = "1.4"